aroundthefire/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import main
from main.views import TripCreate, Index, TripDetail, LocationDetail, \
    LocationCreate, AcceptDecline, ReviewCreate, MessageCreate, AllLocations, \
    UserHome
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Default Url
    url(r'^$', Index.as_view(), name="home"),

    # Admin Urls
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^login', main.views.user_login, name='login'),
    url(r'^admin/', include(admin.site.urls)),

    # User Urls
    url(r'^user/register', main.views.create_camper, name='register'),
    url(r'^user/home', UserHome.as_view(), name='user_home'),

    # Trip Urls
    url(r'^trip/accept_decline/(?P<pk>[0-9]+)/$', AcceptDecline.as_view(),
        name="accept_decline"),
    url(r'^trip/create/$', TripCreate.as_view(),
        name="trip_new"),
    url(r'^trip/(?P<pk>[0-9]+)/$', TripDetail.as_view(), name="trip_detail"),
    url(r'^trip/message/(?P<pk>[0-9]+)/$', MessageCreate.as_view(),
        name="message_create"),
    url(r'^trip/update/(?P<pk>[0-9]+)/$', AcceptDecline.as_view(),
        name="accept_decline"),
    url(r'^trip/invite/$', main.views.invite, name="invite"),

    # Location Urls
    url(r'^locations/$', AllLocations.as_view(), name="locations_all"),
    url(r'^location/(?P<pk>[0-9]+)/$', LocationDetail.as_view(),
        name="location_detail"),
    url(r'^location/new/$', LocationCreate.as_view(), name="location_create"),
    url(r'^location/review/(?P<pk>[0-9]+)/$', ReviewCreate.as_view(),
        name="review_create"),
    url(r'^get_markers/', main.views.get_markers, name="get_markers"),

    # Image Url
    url(r'^image/upload/(?P<pk>[0-9]+)/$', main.views.image_upload,
        name="image_upload"),
]

main/models.py
import datetime
from itertools import chain
from operator import attrgetter
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Model

"""Repeating fields in "Camper" and "Location" are due to Django having
difficulty serializing data in OneToOne objects, so that attempting to pass
a location lat and long in the JS on the template would not work."""


class Camper(models.Model):
    """Model for site user. aka Campers"""

    user = models.OneToOneField(User, null=True)
    zip = models.CharField(max_length=10, null=True, blank=True)
    lat = models.FloatField(max_length=30, null=True)
    lng = models.FloatField(max_length=30, null=True)
    city = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.user.username)

    @property
    def past_trips(self):
        """Get past trips for the camper"""

        return set(sorted(
            chain(self.created.filter(end_date__lte=datetime.datetime.now()),
                  self.attending.filter(end_date__lte=datetime.datetime.now())),
            key=attrgetter('end_date')))

    @property
    def upcoming_trips(self):
        """Get upcoming trips for the camper"""

        return set(sorted(
            chain(self.created.filter(end_date__gt=datetime.datetime.now()),
                  self.attending.filter(end_date__gt=datetime.datetime.now())),
            key=attrgetter('end_date')))

    @property
    def invited_trips(self):
        """Get trips the camper has been invited on that are still upcoming"""

        return set(sorted(
            chain(self.invited.filter(end_date__gt=datetime.datetime.now())),
            key=attrgetter('end_date')))


class UnregisteredUser(models.Model):
    """Model for unregistered users"""

    first_name = models.CharField(max_length=50, null=True)
    email = models.EmailField()


class Trip(models.Model):
    """Model for trips created by campers"""

    owner = models.ForeignKey(Camper, related_name="created", null=True)
    invited = models.ManyToManyField(Camper, related_name='invited', blank=True)
    attending = models.ManyToManyField(Camper, related_name='attending',
                                       blank=True)
    declined = models.ManyToManyField(Camper, related_name='declined',
                                      blank=True)
    unregistered_user = models.ManyToManyField(UnregisteredUser,
                                               related_name='invited',
                                               blank=True)
    start_date = models.DateField(blank=False, null=True)
    end_date = models.DateField(blank=False, null=True)
    location = models.ForeignKey('Location', related_name='location', null=True)
    title = models.CharField(max_length=50, null=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    max_capacity = models.IntegerField(null=True)

    def __str__(self):
        return '{}. {}, {}'.format(self.owner.user.username, self.location,
                                   self.start_date, self.end_date)


class Location(models.Model):
    """Model for campsites"""

    name = models.CharField(max_length=200, null=True)
    zip = models.CharField(max_length=10, null=True, blank=True)
    lat = models.FloatField(max_length=30, null=True)
    lng = models.FloatField(max_length=30, null=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    api_id = models.CharField(max_length=100, unique=True, null=True,
                              blank=True)

    def __str__(self):
        return '{}'.format(self.name)


class Photo(models.Model):
    """Model for photos"""

    location = models.ForeignKey(Location, null=True, blank=True,
                                 related_name='photos')
    trip = models.ForeignKey(Trip, null=True, blank=True, related_name='photos')
    thumbnail = models.URLField(null=True)
    url = models.URLField(null=True)
    created_at = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        ordering = ["-created_at"]


class Message(models.Model):
    """model for messages"""

    owner = models.ForeignKey(Camper, null=True, blank=True,
                              related_name='messages')
    trip = models.ForeignKey(Trip, null=True, blank=True,
                             related_name='messages')
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        ordering = ["-created_at"]


class Review(models.Model):
    """Model for reviews"""

    owner = models.ForeignKey(Camper, null=True, blank=True,
                              related_name='reviews')
    location = models.ForeignKey(Location, null=True, blank=True,
                                 related_name='reviews')
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        ordering = ["-created_at"]

templates/location/all.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block title %}
    Home
{% endblock %}



{% block pane-one-title %}
    Upcoming Trips

{% endblock %}
{% block pane-one %}
    <h4>Invited To <img src="{% static 'img/purplefire.png' %}" class="icon">
    </h4>
    {% if camper.invited.count > 0 %}
        {% for trip in camper.invited_trips %}
            <a href="{% url 'trip_detail' trip.pk %}" class="list-group-item">
                <p>{{ trip.title }}</p>

                <p>{{ trip.location.name }}</p>

                <p>{{ trip.start_date }} - {{ trip.end_date }}</p>


                <form method="post" action="{% url 'accept_decline' trip.pk %}"
                      style="float: left; padding-right: 10px">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="attending">
                    <input type="hidden" name="trip" value="{{ trip.pk }}">
                    <input type="hidden" name="attending"
                           value="{{ camper.pk }}">
                    <input type="submit" value="I'm Going"
                           class="btn btn-xs btn-success">
                </form>

                <form method="post" action="{% url 'accept_decline' trip.pk %}"
                      style="clear: right">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="declined">
                    <input type="hidden" name="trip" value="{{ trip.pk }}">
                    <input type="hidden" name="declined"
                           value="{{ camper.pk }}">
                    <input type="submit" value="Can't Make It"
                           class="btn btn-xs btn-danger">
                </form>

            </a>
        {% endfor %}
    {% else %}
        <p>You Currently Aren't invited On Any Trips</p>
    {% endif %}

    <h4>Upcoming <img src="{% static 'img/redfire.png' %}" class="icon"></h4>
    {% if camper.upcoming_trips %}
        {% for trip in camper.upcoming_trips %}
            <a href="{% url 'trip_detail' trip.pk %}" class="list-group-item">
                <p>What: {{ trip.title }}</p>

                <p>Where: {{ trip.location.name }}</p>

                <p>When: {{ trip.start_date }} - {{ trip.end_date }}</p>

                <p>Created By: {{ trip.owner }}</p>
                {% if trip.attending.all %}
                    <p>Attending: {% for person in trip.attending.all %}
                        {{ person.user.username }}</p>
                    {% endfor %}
                {% else %}
                    <p>No One has accept yet</p>
                {% endif %}
            </a>
        {% endfor %}
    {% else %}

        <p>You Have No Upcoming Trips!</p>
    {% endif %}
{% endblock %}

{% block pane-two-title %}
    Past Trips  <img src="{% static 'img/blackfire.png' %}" class="icon">
{% endblock %}

{% block pane-two %}
    {% if camper.past_trips %}
        {% for trip in camper.past_trips %}
            <a href="{% url 'trip_detail' trip.pk %}" class="list-group-item">
                <p>{{ trip.title }}</p>

                <p>{{ trip.location.name }}</p>

                <p>{{ trip.start_date }} - {{ trip.end_date }}</p>

                <p>{{ trip.owner }}</p>

                <p>{% for person in trip.attending.all %}
                    {{ person.username }}</p>
                {% endfor %}
            </a>
        {% endfor %}
    {% else %}
        <p>You Haven't Been On Any Trips Yet!</p>
    {% endif %}
{% endblock %}

{% block pane-three-title %}

{% endblock %}

{% block pane-three %}
    <iframe id="forecast_embed" type="text/html" frameborder="0" height="245"
            width="100%"
            src="http://forecast.io/embed/#lat={{ camper.lat }}&lon={{ camper.lng }}&name={{ camper.zip }}"></iframe>
{% endblock %}

{% block javascript %}
    <script>
        var iconBase = '{% static 'img/' %}';
        var icons = {
            invited: {
                icon: iconBase + 'purplefire.png'
            },
            upcoming: {
                icon: iconBase + 'redfire.png'
            },
            past: {
                icon: iconBase + 'blackfire.png'
            },
            home: {
                icon: iconBase + 'home.png'
            },
            campsite: {
                icon: iconBase + 'campsite.png'
            }
        };
        var map;
        function initMap() {
            var defautLat = Number({{ user.camper.lat }});
            var defautLng = Number({{ user.camper.lng }});
            var myLatLng2 = {lat: defautLat, lng: defautLng};
            var all;
            map = new google.maps.Map(document.getElementById('map'), {
                zoom: 10,
                center: myLatLng2,
                mapTypeId: google.maps.MapTypeId.TERRAIN
            });
            placeMarker();
            //adds markers for each trip type
            //place a marker on the center of the map
            function placeMarker() {
                var marker = new google.maps.Marker({
                    map: map,
                    position: {
                        lat: defautLat,
                        lng: defautLng
                    },
                    icon: icons['home'].icon
                });
                {#            var infowindow = new google.maps.InfoWindow({#}
                {#                content: (invited[0].fields.name.link('location/'+invited[0].pk))#}
                {##}
                {#            });#}
                {#            google.maps.event.addListener(marker, 'click', function () {#}
                {#                infowindow.open(map, marker);#}
                {#            });#}
            }

            function placeAllMarker(loc) {
                var marker = new google.maps.Marker({
                    map: map,
                    position: {
                        lat: Number(all[loc].fields.lat),
                        lng: Number(all[loc].fields.lng)
                    },
                    icon: icons['campsite'].icon
                });
                var infowindow = new google.maps.InfoWindow({
                    content: (all[loc].fields.name.link('../location/' + all[loc].pk))

                });
                google.maps.event.addListener(marker, 'click', function () {
                    infowindow.open(map, marker);
                });
            }

            google.maps.event.addListener(map, 'idle', function () {
                checkIfMarkersStillVisible();
            });
            function checkIfMarkersStillVisible() {
                coords = map.getBounds();
                zoom = map.getZoom();
                coordsDict = {
                    "n": coords.getNorthEast().lat().toString(),
                    'e': coords.getNorthEast().lng().toString(),
                    's': coords.getSouthWest().lat().toString(),
                    'w': coords.getSouthWest().lng().toString(),
                    'zoom': zoom.toString()
                };

                $.ajax({
                    url: "{% url 'get_markers' %}",
                    dataType: "json",
                    data: coordsDict,
                    success: function (locations) {
                        //loop thought locations and call the marker place functions
                        all = JSON.parse(locations);
                        for (loc in all) {
                            placeAllMarker(loc);
                        }
                    },

                    error: function (xhr, errmsg, err) {
                        console.log(xhr.status + ": " + xhr.responseText)
                    }
                });
            }

            var center;

            function calculateCenter() {
                center = map.getCenter();
            }

            google.maps.event.addDomListener(map, 'idle', function () {
                calculateCenter();
            });
            google.maps.event.addDomListener(window, 'resize', function () {
                map.setCenter(center);
            });
        }

        $(function () {
            $('#pane-one').removeClass('hidden');
        });
        $(function () {
            $('#pane-two').removeClass('hidden');
        });
        $(function () {
            $('#pane-three').removeClass('hidden');
        });
    </script>
{% endblock %}

templates/location/detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block title %}
    {{ location.name }}
{% endblock %}
{% block head %}
<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<link rel="stylesheet" href="{% static "css/bootstrap-image-gallery.min.css"%}">
{% endblock %}

{% block body %}
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}



{% block pane-one-title %}
    {{ location.name }}
{% endblock %}

{% block pane-one %}
    <h4 class="location-city">{{ location.city }}</h4>
    {% if user.id %}
        <p class="trip-create"><button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#createTripModal" value="Create a Trip Here">Create A Trip Here</button><p></p>
    {% else %}
            <h5>To Create a trip here please <a href='' data-toggle="modal" data-target="#LoginModal">Login</a> or <a href='' data-toggle="modal" data-target="#registerModal">Sign Up!</a></h5>
    {% endif %}
    <hr>
    {% if photos %}
        <div id="photogrid">
            {% for photo in photos %}
                <a href="{{ photo.url }}" title="{{ location.name }}" data-gallery>
                    <img class ="thumbnails" src="{{ photo.thumbnail }}" alt="{{ location.name }}">
                </a>
            {% endfor %}
        </div>

    {% else %}
        <p>There Are No Photos For This Location</p>
    {% endif %}
    {% if user.id %}
    <P><a class="btn btn-info btn-sm" href="#" id="upload_widget_opener">Upload A Photo</a></p>
        <script src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>

        <script type="text/javascript">
          document.getElementById("upload_widget_opener").addEventListener("click", function() {

            cloudinary.openUploadWidget({ cloud_name: 'dl5issl9q', upload_preset: 'u8y6ymge', theme: 'minimal'},
              function(error, result) {
                  var imgResult = {sites: [], type: 'location'};
                for (idx in result) {
                    var image = result[idx];
                    imgResult['sites'].push({'thumbnail': image['thumbnail_url'], 'url': image['url']});
                }
                  console.log(JSON.stringify(imgResult));
                   $.post(
                       '/image/upload/' + '{{ location.pk }}' + '/',
                       JSON.stringify(imgResult),
                       function() { $('#results').html("DONE") }
                    );
                    location.reload()
              });

          }, false);
        </script>
    {% endif %}
{% endblock %}


{% block pane-two-title %}
    Reviews
{% endblock %}

{% block pane-two %}

     {% if location.reviews.all %}
        <h4>Most Recent Review</h4>
        <h5>{{ location.reviews.all.0.owner }} @ {{ location.reviews.all.0.created_at }}</h5>
        <p>{{ location.reviews.all.0.content }}</p>
        <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">See All Reviews</button>
    {% else %}
        <h5>There are no reviews for this location</h5>
         {% if user.id %}
            <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal">Leave A Review</button>
         {% endif %}
    {% endif %}

{% endblock %}

{% block pane-three-title %}

{% endblock %}

{% block pane-three %}
    <iframe id="forecast_embed" type="text/html" frameborder="0" height="245"
            width="100%"
            src="http://forecast.io/embed/#lat={{ location.lat }}&lon={{ location.lng }}&name={{ location.name }}"></iframe>
{% endblock %}

{% block modal %}
    <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">User Reviews</h4>
      </div>
      <div class="modal-body">
      {% if user.id %}
            <h4>Been Here? Leave a Review!</h4>
            <form method="post" action="{% url 'review_create' pk=location.pk %}">
            {% csrf_token %}
                <div class="form-group">
                <label for="reviewContent">How Was Your Trip?</label>
                <textarea name='content' class="form-control" id="reviewContent" placeholder="Here's my Story" rows="3"></textarea>
                <input type="hidden" name='location' value="{{ location.pk }}">
                </div>
                <input type="submit" value="Leave A Review" class="btn btn-success">
            </form>
      {% endif %}
        {% for review in location.reviews.all %}
          <h5>{{ review.owner }} @ {{ review.created_at }}</h5>
          <p>{{ review.content }}</p>
        {% endfor %}

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
    <div id="createTripModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Trip Messages</h4>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'trip_new' %}">
        {% csrf_token %}
            <input name="location" type="hidden" value="{{ location.pk }}"/>
            <div class="form-group"><label class="sr-only" for="id_start_date">Start date</label><input class="form-control" id="id_start_date" name="start_date" placeholder="Start date" required="required" title="" type="text" /></div>
            <div class="form-group"><label class="sr-only" for="id_end_date">End date</label><input class="form-control" id="id_end_date" name="end_date" placeholder="End date" required="required" title="" type="text" /></div>
            <div class="form-group"><label class="sr-only" for="id_title">Title</label><input class="form-control" id="id_title" maxlength="50" name="title" placeholder="Title" required="required" title="" type="text" /></div>
            <div class="form-group"><label class="sr-only" for="id_max_capacity">Max capacity</label><input class="form-control" id="id_max_capacity" name="max_capacity" placeholder="Max capacity" required="required" title="" type="number" /></div>
            <div class="form-group"><label class="sr-only" for="id_description">Description</label><textarea class="form-control" cols="40" id="id_description" maxlength="500" name="description" placeholder="Description" rows="10" title=""></textarea></div>
            <input type="submit" value="Create A Trip" class="btn btn-success"> <span style="float: right"> Next: Invite Your Friends!</span>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block javascript %}
<script>
    var iconBase = '{% static "img/" %}';
    var icons = {
      invited: {
        icon: iconBase + 'purplefire.png'
      },
      upcoming: {
        icon: iconBase + 'redfire.png'
      },
      past: {
        icon: iconBase + 'blackfire.png'
      },
      home: {
          icon: iconBase + 'home.png'
      },
      campsite: {
          icon: iconBase + 'campsite.png'
      }
    };
    function initMap() {
        var defautLat = Number({{ location.lat }});
        var defautLng = Number({{ location.lng }});
        var myLatLng2 = {lat: defautLat, lng: defautLng};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 16,
            center: myLatLng2,
            mapTypeId: google.maps.MapTypeId.SATELLITE
        });
        //loop thought locations and call the marker place functions

        placeMarker();

        //adds markers for each trip type
        //place a marker on the center of the map
        function placeMarker() {
            var marker = new google.maps.Marker({
                map: map,
                position: {
                    lat: defautLat,
                    lng: defautLng
                },
                icon: icons['campsite'].icon
            });
            var infowindow = new google.maps.InfoWindow({
                content: ('{{ location.name }}')


            });
            google.maps.event.addListener(marker, 'click', function () {
                infowindow.open(map, marker);
            });
        }
        var center;
            function calculateCenter() {
              center = map.getCenter();
            }
            google.maps.event.addDomListener(map, 'idle', function() {
              calculateCenter();
            });
            google.maps.event.addDomListener(window, 'resize', function() {
              map.setCenter(center);
            });
    }

    $(function () {
     $('#pane-one').removeClass('hidden');
     });
    $(function () {
         $('#pane-two').removeClass('hidden');
     });
    $(function () {
         $('#pane-three').removeClass('hidden');
     });
</script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<script src="{% static "js/bootstrap-image-gallery.min.js" %}"></script>
{% endblock %}