aroundthefire/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import main
from main.views import TripCreate, Index, TripDetail, LocationDetail, \
    LocationCreate, AcceptDecline, ReviewCreate, MessageCreate, AllLocations, \
    UserHome
from django.contrib.auth import views as auth_views

urlpatterns = [
    # Default Url
    url(r'^$', Index.as_view(), name="home"),

    # Admin Urls
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^login', main.views.user_login, name='login'),
    url(r'^admin/', include(admin.site.urls)),

    # User Urls
    url(r'^user/register', main.views.create_camper, name='register'),
    url(r'^user/home', UserHome.as_view(), name='user_home'),

    # Trip Urls
    url(r'^trip/accept_decline/(?P<pk>[0-9]+)/$', AcceptDecline.as_view(),
        name="accept_decline"),
    url(r'^trip/create/$', TripCreate.as_view(),
        name="trip_new"),
    url(r'^trip/(?P<pk>[0-9]+)/$', TripDetail.as_view(), name="trip_detail"),
    url(r'^trip/message/(?P<pk>[0-9]+)/$', MessageCreate.as_view(),
        name="message_create"),
    url(r'^trip/update/(?P<pk>[0-9]+)/$', AcceptDecline.as_view(),
        name="accept_decline"),
    url(r'^trip/invite/$', main.views.invite, name="invite"),

    # Location Urls
    url(r'^locations/$', AllLocations.as_view(), name="locations_all"),
    url(r'^location/(?P<pk>[0-9]+)/$', LocationDetail.as_view(),
        name="location_detail"),
    url(r'^location/new/$', LocationCreate.as_view(), name="location_create"),
    url(r'^location/review/(?P<pk>[0-9]+)/$', ReviewCreate.as_view(),
        name="review_create"),
    url(r'^get_markers/', main.views.get_markers, name="get_markers"),

    # Image Url
    url(r'^image/upload/(?P<pk>[0-9]+)/$', main.views.image_upload,
        name="image_upload"),
]

main/models.py
import datetime
from itertools import chain
from operator import attrgetter
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Model

"""Repeating fields in "Camper" and "Location" are due to Django having
difficulty serializing data in OneToOne objects, so that attempting to pass
a location lat and long in the JS on the template would not work."""


class Camper(models.Model):
    """Model for site user. aka Campers"""

    user = models.OneToOneField(User, null=True)
    zip = models.CharField(max_length=10, null=True, blank=True)
    lat = models.FloatField(max_length=30, null=True)
    lng = models.FloatField(max_length=30, null=True)
    city = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.user.username)

    @property
    def past_trips(self):
        """Get past trips for the camper"""

        return set(sorted(
            chain(self.created.filter(end_date__lte=datetime.datetime.now()),
                  self.attending.filter(end_date__lte=datetime.datetime.now())),
            key=attrgetter('end_date')))

    @property
    def upcoming_trips(self):
        """Get upcoming trips for the camper"""

        return set(sorted(
            chain(self.created.filter(end_date__gt=datetime.datetime.now()),
                  self.attending.filter(end_date__gt=datetime.datetime.now())),
            key=attrgetter('end_date')))

    @property
    def invited_trips(self):
        """Get trips the camper has been invited on that are still upcoming"""

        return set(sorted(
            chain(self.invited.filter(end_date__gt=datetime.datetime.now())),
            key=attrgetter('end_date')))


class UnregisteredUser(models.Model):
    """Model for unregistered users"""

    first_name = models.CharField(max_length=50, null=True)
    email = models.EmailField()


class Trip(models.Model):
    """Model for trips created by campers"""

    owner = models.ForeignKey(Camper, related_name="created", null=True)
    invited = models.ManyToManyField(Camper, related_name='invited', blank=True)
    attending = models.ManyToManyField(Camper, related_name='attending',
                                       blank=True)
    declined = models.ManyToManyField(Camper, related_name='declined',
                                      blank=True)
    unregistered_user = models.ManyToManyField(UnregisteredUser,
                                               related_name='invited',
                                               blank=True)
    start_date = models.DateField(blank=False, null=True)
    end_date = models.DateField(blank=False, null=True)
    location = models.ForeignKey('Location', related_name='location', null=True)
    title = models.CharField(max_length=50, null=True)
    description = models.TextField(max_length=500, null=True, blank=True)
    max_capacity = models.IntegerField(null=True)

    def __str__(self):
        return '{}. {}, {}'.format(self.owner.user.username, self.location,
                                   self.start_date, self.end_date)


class Location(models.Model):
    """Model for campsites"""

    name = models.CharField(max_length=200, null=True)
    zip = models.CharField(max_length=10, null=True, blank=True)
    lat = models.FloatField(max_length=30, null=True)
    lng = models.FloatField(max_length=30, null=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    api_id = models.CharField(max_length=100, unique=True, null=True,
                              blank=True)

    def __str__(self):
        return '{}'.format(self.name)


class Photo(models.Model):
    """Model for photos"""

    location = models.ForeignKey(Location, null=True, blank=True,
                                 related_name='photos')
    trip = models.ForeignKey(Trip, null=True, blank=True, related_name='photos')
    thumbnail = models.URLField(null=True)
    url = models.URLField(null=True)
    created_at = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        ordering = ["-created_at"]


class Message(models.Model):
    """model for messages"""

    owner = models.ForeignKey(Camper, null=True, blank=True,
                              related_name='messages')
    trip = models.ForeignKey(Trip, null=True, blank=True,
                             related_name='messages')
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        ordering = ["-created_at"]


class Review(models.Model):
    """Model for reviews"""

    owner = models.ForeignKey(Camper, null=True, blank=True,
                              related_name='reviews')
    location = models.ForeignKey(Location, null=True, blank=True,
                                 related_name='reviews')
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        ordering = ["-created_at"]

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from main.models import Trip


class CamperCreateForm(UserCreationForm):
    """Form for registering New Campers"""

    zip = forms.CharField(max_length=10, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class TripCreateForm(ModelForm):
    """Form for creating a new trip"""

    model = Trip
    fields = ('date',)

templates/default.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block title %}
    The Place for Camping
{% endblock %}

{% block head %}
<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<link rel="stylesheet" href="{% static "css/bootstrap-image-gallery.min.css"%}">
{% endblock %}

{% block body %}
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block pane-one %}
    <h3> Welcome To Around The Fire</h3>
    <h4>The Place To Organize Your Camping Trips</h4>
    <p>Have a look around! Click any campsite on the map to view pictures and reviews.</p>
    <h5>To create a trip please, <a href='' data-toggle="modal" data-target="#LoginModal">Login</a> or <a href='' data-toggle="modal" data-target="#registerModal">Sign Up!</a></h5>
{% endblock %}

{% block pane-two-title %}
    <h4>Most Recent Pictures</h4>
{% endblock %}
{% block pane-two %}

        <div id="photogrid">
            {% for photo in photos %}
                <a href="{{ photo.url }}" title="{{ photo.location.name }}" data-gallery>
                    <img class ="thumbnails" src="{{ photo.thumbnail }}" alt="{{ location.name }}">
                </a>
            {% endfor %}
        </div>

{% endblock %}

{% block pane-three %}
    <iframe id="forecast_embed" type="text/html" frameborder="0" height="245" width="100%" src="http://forecast.io/embed/#lat=36.1&lon=-115.15&name=Las Vegas"> </iframe>
{% endblock %}

{% block javascript %}
<script>
var iconBase = '{% static 'img/' %}';
var icons = {
  invited: {
    icon: iconBase + 'purplefire.png'
  },
  upcoming: {
    icon: iconBase + 'redfire.png'
  },
  past: {
    icon: iconBase + 'blackfire.png'
  },
  home: {
    icon: iconBase + 'home.png'
  },
  campsite: {
      icon: iconBase + 'campsite.png'
  }
};
var map;
function initMap() {
    var defautLat = Number(36.1);
    var defautLng = Number(-115.15);
    var myLatLng2 = {lat: defautLat, lng: defautLng};
    var all;
    map = new google.maps.Map(document.getElementById('map'), {
        zoom: 8,
        center: myLatLng2,
        mapTypeId: google.maps.MapTypeId.TERRAIN
    });
    //adds markers for each trip type
    //place a marker on the center of the map
    function placeAllMarker(loc) {
        var marker = new google.maps.Marker({
            map: map,
            position: {
                lat: Number(all[loc].fields.lat),
                lng: Number(all[loc].fields.lng)
            },
            icon: icons['campsite'].icon
        });
        var infowindow = new google.maps.InfoWindow({
            content: (all[loc].fields.name.link('../location/'+all[loc].pk))

        });
        google.maps.event.addListener(marker, 'click', function () {
            infowindow.open(map, marker);
        });
    }

    google.maps.event.addListener(map, 'idle', function() {
        checkIfMarkersStillVisible();
    });
    function checkIfMarkersStillVisible() {
        coords =  map.getBounds();
        zoom = map.getZoom();
        coordsDict = {"n": coords.getNorthEast().lat().toString(),
            'e': coords.getNorthEast().lng().toString(),
            's': coords.getSouthWest().lat().toString(),
            'w': coords.getSouthWest().lng().toString(),
            'zoom': zoom.toString()};

        $.ajax({
            url: "{% url 'get_markers' %}",
            dataType: "json",
            data: coordsDict,
            success : function(locations) {
                //loop thought locations and call the marker place functions
                all = JSON.parse(locations);
                for (loc in all) {
                    placeAllMarker(loc);}
                },

            error : function(xhr,errmsg,err) {
                console.log(xhr.status + ": " + xhr.responseText)
            }
        });
    }

    var center;
    function calculateCenter() {
          center = map.getCenter();
        }
        google.maps.event.addDomListener(map, 'idle', function() {
          calculateCenter();
        });
        google.maps.event.addDomListener(window, 'resize', function() {
          map.setCenter(center);
    });
}

    $(function () {
     $('#pane-one').removeClass('hidden');
     });
    $(function () {
         $('#pane-two').removeClass('hidden');
     });

</script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<script src="{% static "js/bootstrap-image-gallery.min.js" %}"></script>
{% endblock %}

{% block modal %}
<div class="container">

  <!-- Modal -->
  <div class="modal fade" id="registerModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 style="color:red; "><span class="glyphicon glyphicon-lock"></span> Register</h4>
        </div>
        <div class="modal-body">


            <form action="{% url 'register' %}" method = 'POST'>
                {% csrf_token %}
                <input type="hidden" name="next" value="/">
                <div class="form-group"><label class="sr-only" for="id_username">Username</label><input class="form-control" id="id_username" maxlength="254" name="username" placeholder="Username" required="required" title="" type="text" /></div>
                <div class="form-group"><label class="sr-only" for="id_first_name">First Name</label><input class="form-control" id="id_first_name" maxlength="30" name="first_name" placeholder="First Name" required="required" title="" type="text" /></div>
                <div class="form-group"><label class="sr-only" for="id_last_name">Last Name</label><input class="form-control" id="id_last_name" maxlength="30" name="last_name" placeholder="Last Name" required="required" title="" type="text" /></div>

                <div class="form-group"><label class="sr-only" for="id_email">email</label><input class="form-control" id="id_email" maxlength="254" name="email" placeholder="email" required="required" title="" type="emmail" /></div>
                <div class="form-group"><label class="sr-only" for="id_zip">Username</label><input class="form-control" id="id_zip" maxlength="10" name="zip" placeholder="ZipCode" required="required" title="" type="number" /></div>
                <div class="form-group"><label class="sr-only" for="id_password">Password</label><input class="form-control" id="id_password" name="password1" placeholder="Password" required="required" title="" type="password" /></div>
                <div class="form-group"><label class="sr-only" for="id_password">Password</label><input class="form-control" id="id_password" name="password2" placeholder="Password" required="required" title="" type="password" /></div>


                <input type = 'submit' value="Register" class="btn btn-danger"/>
            </form>

            <div class="checkbox">
              <label><input type="checkbox" value="" checked>Remember me</label>
            </div>
            <button type="submit" class="btn btn-default btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-default btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
          <p>Not a member? <a href="{% url 'register' %}">Sign Up</a></p>
          <p>Forgot <a href="#">Password?</a></p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Simple markers</title>
    <style>
      html, body {
        height: 70%;
        width: 70%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>

function initMap() {
    var myLatLng = {lat: 36.363, lng: -115.044};
    var myLatLng2 = {lat: 36.365, lng: -115.064};

    var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 4,
        center: myLatLng
    });

    var infowindow = new google.maps.InfoWindow({
        content: 'check check check'
    });

    var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Hello World!'
    });

    var marker2 = new google.maps.Marker({
        position: myLatLng2,
        map: map,
        title: 'Hello World2222!'
    });

    marker.addListener('click', function () {
        infowindow.open(map, marker)
    });
}

    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap"></script>
  </body>
</html>